data: 
  num_train_files: 400
  num_val_files: 100
  batch_size: 1024
  shuffle: False
  num_procs: 32
  preprocess: True
  output_dir: "output"  
  already_preprocessed: False


model:
  block_type: graphnet
  concat_input: true
  edge_block_opt: {use_edges: true, use_globals: true, use_receiver_nodes: true, use_sender_nodes: true}
  global_block_opt: {use_edges: false, use_globals: true, use_nodes: true}
  latent_size: 64
  node_block_opt: {use_globals: true, use_nodes: true, use_received_edges: true, use_sent_edges: false}
  num_blocks: 4
  num_layers: 4
  reducer: mean
